import { useState } from 'react';

export default function ExportButton({ sections, values, selectedIndustry, industries, overallScore }) {
  const [copied, setCopied] = useState(false);
  const industry = industries.find((i) => i.id === selectedIndustry);

  function generateTextPlan() {
    const actionItems = [];
    sections.forEach((section) => {
      section.items.forEach((item) => {
        const val = values[item.id];
        let isComplete = false;
        if (item.type === 'checkbox') isComplete = !!val;
        else if (item.type === 'number') isComplete = val >= item.target;

        if (!isComplete) {
          actionItems.push({
            ...item,
            sectionTitle: section.title,
          });
        }
      });
    });

    actionItems.sort((a, b) => {
      if (b.impact !== a.impact) return b.impact - a.impact;
      return b.points - a.points;
    });

    let text = `GOOGLE BUSINESS PROFILE OPTIMIZATION PLAN\n`;
    text += `==========================================\n\n`;
    text += `Overall Score: ${overallScore}/100\n`;
    if (industry) text += `Industry: ${industry.name}\n`;
    text += `Date: ${new Date().toLocaleDateString()}\n`;
    text += `Items to improve: ${actionItems.length}\n\n`;

    // Section scores
    text += `SECTION SCORES\n`;
    text += `--------------\n`;
    sections.forEach((section) => {
      const sectionScore = section.items.reduce((acc, item) => {
        const val = values[item.id];
        if (item.type === 'checkbox' && val) return acc + item.points;
        if (item.type === 'number') {
          if (val >= item.target) return acc + item.points;
          if (val > 0) return acc + Math.round(item.points * (val / item.target));
        }
        return acc;
      }, 0);
      const percent = Math.round((sectionScore / section.maxPoints) * 100);
      const status = percent >= 80 ? 'DONE' : percent >= 50 ? 'IN PROGRESS' : 'NEEDS WORK';
      text += `  ${section.title}: ${sectionScore}/${section.maxPoints} pts (${percent}%) — ${status}\n`;
    });

    text += `\nACTION ITEMS (sorted by impact)\n`;
    text += `-------------------------------\n\n`;

    const impactLabels = { 3: 'HIGH IMPACT', 2: 'MEDIUM IMPACT', 1: 'LOW IMPACT' };
    [3, 2, 1].forEach((impact) => {
      const items = actionItems.filter((a) => a.impact === impact);
      if (items.length === 0) return;

      text += `--- ${impactLabels[impact]} ---\n\n`;
      items.forEach((item, idx) => {
        text += `${idx + 1}. ${item.label}\n`;
        text += `   Section: ${item.sectionTitle}\n`;
        text += `   Points: +${item.points}\n`;
        text += `   What to do: ${item.actionText}\n`;
        text += `   Why: ${item.whyItMatters}\n`;
        text += `   GBP Link: ${item.gbpLink}\n\n`;
      });
    });

    if (industry) {
      text += `\nINDUSTRY TIPS FOR ${industry.name.toUpperCase()}\n`;
      text += `${'—'.repeat(30)}\n`;
      industry.tips.forEach((tip, idx) => {
        text += `${idx + 1}. ${tip}\n`;
      });
    }

    text += `\n\n---\nGenerated by DreamHost Free Tools\nhttps://seo-tools-tau.vercel.app/local-business/\n`;

    return text;
  }

  async function handleCopy() {
    const text = generateTextPlan();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  }

  function handlePrint() {
    window.print();
  }

  return (
    <div className="flex flex-col sm:flex-row gap-3 no-print">
      <button
        onClick={handleCopy}
        className={`flex items-center justify-center gap-2 px-5 py-3 rounded-lg font-semibold text-sm transition-all cursor-pointer ${
          copied
            ? 'bg-turtle text-white'
            : 'bg-azure text-white hover:bg-azure-hover'
        } focus:ring-2 focus:ring-azure focus:ring-offset-2 focus:ring-offset-abyss`}
      >
        {copied ? (
          <>
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
            </svg>
            Copied to Clipboard
          </>
        ) : (
          <>
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9.75a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
            </svg>
            Copy Action Plan
          </>
        )}
      </button>

      <button
        onClick={handlePrint}
        className="flex items-center justify-center gap-2 px-5 py-3 rounded-lg font-semibold text-sm border border-metal/30 text-cloudy hover:text-white hover:border-metal/50 transition-all cursor-pointer focus:ring-2 focus:ring-azure focus:ring-offset-2 focus:ring-offset-abyss"
      >
        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5zm-3 0h.008v.008H15V10.5z" />
        </svg>
        Print Action Plan
      </button>
    </div>
  );
}
